# Generated by Django 5.2.3 on 2025-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='escalation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
