# Generated by Django 5.2.3 on 2025-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_candidate_escalation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_language',
            field=models.CharField(default='it', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='processed_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
